### ISSUE TITLE
Not working w/CTFd 3.1.1 - AttributeError: 'result' object has no attribute 'tag'

### ISSUE THREAD

**Issue by zevlag** [tamuctf/portable-challenges-plugin#11]
I get the following errors when trying to `export` on CTFd 3.11

```python
ctfd_1     | ERROR [CTFd] Exception on /admin/yaml [GET]
ctfd_1     | Traceback (most recent call last):
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
ctfd_1     |     response = self.full_dispatch_request()
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
ctfd_1     |     rv = self.handle_user_exception(e)
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
ctfd_1     |     return original_handler(e)
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
ctfd_1     |     reraise(exc_type, exc_value, tb)
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1     |     raise value
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd_1     |     rv = self.dispatch_request()
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd_1     |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1     |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 110, in admins_only_wrapper
ctfd_1     |     return f(*args, **kwargs)
ctfd_1     |   File "/opt/CTFd/CTFd/plugins/ctfd-portable-challenges-plugin/portable.py", line 26, in transfer_yaml
ctfd_1     |     yamlfile.write(bytes(export_challenges('export.yaml', 'export.d', upload_folder, tarball), "UTF-8"))
ctfd_1     |   File "/opt/CTFd/CTFd/plugins/ctfd-portable-challenges-plugin/exporter.py", line 95, in export_challenges
ctfd_1     |     tags = [tag.tag for tag in Tags.query.add_columns('value').filter_by(challenge_id=chal.id).all()]
ctfd_1     |   File "/opt/CTFd/CTFd/plugins/ctfd-portable-challenges-plugin/exporter.py", line 95, in <listcomp>
ctfd_1     |     tags = [tag.tag for tag in Tags.query.add_columns('value').filter_by(challenge_id=chal.id).all()]
ctfd_1     | AttributeError: 'result' object has no attribute 'tag'
```

**Comment by cpeter** [comment]
Fixed in the latest version.

**Comment by cpeter** [comment]
thx for flagging.

**Comment by zevlag** [comment]
Thanks for addressing this so quickly. You’re awesome.
