### ISSUE TITLE
Fail to run on command line

### ISSUE THREAD

**Issue by dakiro** [tamuctf/portable-challenges-plugin#8]
Works perfectly in ctfd but fail in command line :

```
/opt/CTFd/CTFd/plugins/ctfd-portable-challenges-plugin # ./exporter.py -o /tmp/test.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 818, in configure_subclass_mapper
    sub_mapper = mapper.polymorphic_map[discriminator]
KeyError: 'multiple_choice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./exporter.py", line 161, in <module>
    out_stream.write(export_challenges(args.out_file, args.dst_attachments, args.src_attachments, tarfile))
  File "./exporter.py", line 66, in export_challenges
    chals = Challenges.query.order_by(Challenges.value).all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3211, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 841, in polymorphic_instance
    _instance = polymorphic_instances[discriminator]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 734, in __missing__
    self[key] = val = self.creator(key)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 821, in configure_subclass_mapper
    "No such polymorphic_identity %r is defined" % discriminator
AssertionError: No such polymorphic_identity 'multiple_choice' is defined

```

**Comment by cpeter** [comment]
@dakiro you might have the Multiple Choice Challenge Plugin installed. I do not have the plugin neither have I tested with that custom plugin.

**Comment by dakiro** [comment]
I understand, it works via api ... 
If I can help in any way to troubleshoot don't hesitate.

**Comment by cpeter** [comment]
I can have a look if you can give me access to a ctfd install with the plugin installed or you can provide access to the plugin itself.
My assumption is that when you run via the cli the multi choice plugin is not loaded and it wouldn't because it's not part of the standard distro.

**Comment by cpeter** [comment]
I can't test with Multiple Choice Challenge Plugin and reported did not provided a way for me to test it. Will close this issue for now.
